name: flutter_junior_surf
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  bloc: ^8.0.1
  dartz: ^0.10.1
  dio: ^4.0.4
  email_validator: ^2.0.1
  faker: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^1.1.0
  intl: ^0.17.0
  json_serializable: ^6.1.1
  shared_preferences: ^2.0.11
  sizer: ^2.0.15

dev_dependencies:
  bloc_test: ^9.0.1
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  golden_toolkit: ^0.12.0
  integration_test:
    sdk: flutter
  json_annotation: ^4.4.0
  mocktail: ^0.2.0
  surf_lint_rules: ^1.4.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - background.png
    - bx_user_circle.png
    - warning-sign 1.png

