name: flutter_junior_surf
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  bloc: ^7.2.1
  dartz: ^0.10.0
  dio: ^4.0.0
  email_validator: ^2.0.1
  faker: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^0.15.0
  intl: ^0.17.0
  json_serializable: ^5.0.2
  sizer: ^2.0.15

dev_dependencies:
  bloc_test: ^8.3.0
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  freezed: ^0.15.0+1
  json_annotation: ^4.1.0
  mocktail: ^0.1.1
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - background.png

